package validate

import (
	"encoding/json"
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

const specVersion = 1

// Spec is the expectation file loaded from YAML or JSON.
type Spec struct {
	Version     int        `yaml:"version"     json:"version"`
	Description string     `yaml:"description"  json:"description,omitempty"`
	Schema      SchemaSpec `yaml:"schema"       json:"schema"`
	Data        DataSpec   `yaml:"data"         json:"data,omitempty"`
}

type SchemaSpec struct {
	AddedTables    []string      `yaml:"added_tables"    json:"added_tables,omitempty"`
	RemovedTables  []string      `yaml:"removed_tables"  json:"removed_tables,omitempty"`
	ModifiedTables []TableChange `yaml:"modified_tables" json:"modified_tables,omitempty"`
}

type TableChange struct {
	Table          string        `yaml:"table"            json:"table"`
	AddedColumns   []ColumnSpec  `yaml:"added_columns"    json:"added_columns,omitempty"`
	RemovedColumns []ColumnSpec  `yaml:"removed_columns"  json:"removed_columns,omitempty"`
	AddedIndexes   []IndexSpec   `yaml:"added_indexes"    json:"added_indexes,omitempty"`
	RemovedIndexes []IndexSpec   `yaml:"removed_indexes"  json:"removed_indexes,omitempty"`
}

type ColumnSpec struct {
	Name string `yaml:"name" json:"name"`
	Type string `yaml:"type" json:"type,omitempty"`
}

type IndexSpec struct {
	Name   string `yaml:"name"   json:"name"`
	Unique bool   `yaml:"unique" json:"unique,omitempty"`
}

type DataSpec map[string]TableDataSpec

type TableDataSpec struct {
	MinRows *int64 `yaml:"min_rows" json:"min_rows,omitempty"`
	MaxRows *int64 `yaml:"max_rows" json:"max_rows,omitempty"`
}

// LoadSpec reads a YAML or JSON expectation file.
func LoadSpec(path string) (*Spec, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading spec file: %w", err)
	}

	var spec Spec

	// Detect format by extension
	if len(path) > 5 && path[len(path)-5:] == ".json" {
		if err := json.Unmarshal(data, &spec); err != nil {
			return nil, fmt.Errorf("parsing JSON spec: %w", err)
		}
	} else {
		if err := yaml.Unmarshal(data, &spec); err != nil {
			return nil, fmt.Errorf("parsing YAML spec: %w", err)
		}
	}

	if spec.Version == 0 {
		spec.Version = specVersion
	}

	return &spec, nil
}

// WriteSpec writes a spec to a YAML file.
func WriteSpec(path string, spec *Spec) error {
	data, err := yaml.Marshal(spec)
	if err != nil {
		return fmt.Errorf("marshaling spec: %w", err)
	}
	header := []byte("# Generated by litescope validate init\n# Edit to match your expected migration changes.\n\n")
	return os.WriteFile(path, append(header, data...), 0644)
}
