// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audit} from '../models';
import {main} from '../models';
import {check} from '../models';
import {diff} from '../models';
import {monitor} from '../models';
import {schema} from '../models';

export function AuditLog(arg1:number,arg2:string,arg3:string):Promise<Array<audit.Entry>>;

export function BrowseTable(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:boolean,arg7:string):Promise<main.TableRows>;

export function Check(arg1:string,arg2:string,arg3:boolean):Promise<check.Result>;

export function DeleteRow(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Diff(arg1:string,arg2:string):Promise<diff.Result>;

export function ExportSQL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ExportResult>;

export function FleetCheck(arg1:Array<main.FleetDBEntry>):Promise<Array<main.FleetCheckResult>>;

export function FleetConverge(arg1:Array<main.FleetDBEntry>,arg2:boolean,arg3:boolean):Promise<main.FleetConvergeResult>;

export function FleetDiscover(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.FleetDBEntry>>;

export function FleetFingerprint(arg1:Array<main.FleetDBEntry>):Promise<main.FleetFingerprintResult>;

export function FleetHealth(arg1:Array<main.FleetDBEntry>,arg2:boolean):Promise<Array<main.FleetHealthResult>>;

export function FleetLoadConfig(arg1:string):Promise<Array<main.FleetDBEntry>>;

export function FleetRecover(arg1:Array<main.FleetDBEntry>,arg2:boolean):Promise<Array<main.FleetRecoverResult>>;

export function FleetSnapshot(arg1:Array<main.FleetDBEntry>):Promise<Array<main.FleetSnapshotResult>>;

export function FleetTopology(arg1:Array<main.FleetDBEntry>):Promise<main.FleetTopologyResult>;

export function InsertRow(arg1:string,arg2:string):Promise<number>;

export function MigrateApply(arg1:string,arg2:string,arg3:boolean):Promise<main.MigrateApplyResult>;

export function MigrateGenerate(arg1:string,arg2:string):Promise<main.MigratePreview>;

export function MonitorCheck(arg1:string,arg2:string):Promise<monitor.DriftResult>;

export function MonitorLoadHistory(arg1:string):Promise<Array<monitor.HistoryEntry>>;

export function MonitorSnapshot(arg1:string,arg2:string):Promise<main.SnapshotInfo>;

export function MonitorWatchIsRunning():Promise<boolean>;

export function MonitorWatchStart(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function MonitorWatchStop():Promise<void>;

export function OpenFile():Promise<string>;

export function OpenFleetConfig():Promise<string>;

export function RunSQL(arg1:string,arg2:string,arg3:boolean):Promise<main.SQLResult>;

export function SaveFile(arg1:string):Promise<string>;

export function Schema(arg1:string):Promise<schema.Schema>;

export function TableDiffRows(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<main.DiffedRow>>;

export function UpdateCell(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:boolean):Promise<void>;
