// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {diff} from '../models';
import {schema} from '../models';

export function Diff(arg1:string,arg2:string):Promise<diff.Result>;

export function OpenFile():Promise<string>;

export function Schema(arg1:string):Promise<schema.Schema>;
