// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {check} from '../models';
import {diff} from '../models';
import {main} from '../models';
import {monitor} from '../models';
import {schema} from '../models';

export function Check(arg1:string,arg2:string,arg3:boolean):Promise<check.Result>;

export function Diff(arg1:string,arg2:string):Promise<diff.Result>;

export function MigrateApply(arg1:string,arg2:string,arg3:boolean):Promise<main.MigrateApplyResult>;

export function MigrateGenerate(arg1:string,arg2:string):Promise<main.MigratePreview>;

export function MonitorCheck(arg1:string,arg2:string):Promise<monitor.DriftResult>;

export function MonitorLoadHistory(arg1:string):Promise<Array<monitor.HistoryEntry>>;

export function MonitorSnapshot(arg1:string,arg2:string):Promise<main.SnapshotInfo>;

export function MonitorWatchStart(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function MonitorWatchStop():Promise<void>;

export function MonitorWatchIsRunning():Promise<boolean>;

export function FleetDiscover(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.FleetDBEntry>>;

export function FleetSnapshot(arg1:Array<main.FleetDBEntry>):Promise<Array<main.FleetSnapshotResult>>;

export function FleetCheck(arg1:Array<main.FleetDBEntry>):Promise<Array<main.FleetCheckResult>>;

export function FleetFingerprint(arg1:Array<main.FleetDBEntry>):Promise<any>;

export function FleetConverge(arg1:Array<main.FleetDBEntry>,arg2:boolean,arg3:boolean):Promise<any>;

export function FleetHealth(arg1:Array<main.FleetDBEntry>,arg2:boolean):Promise<Array<any>>;

export function FleetRecover(arg1:Array<main.FleetDBEntry>,arg2:boolean):Promise<Array<any>>;

export function OpenFile():Promise<string>;

export function QueryTable(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.TableRows>;

export function SaveFile(arg1:string):Promise<string>;

export function Schema(arg1:string):Promise<schema.Schema>;

export function TableDiffRows(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<main.DiffedRow>>;
