// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1, arg2, arg3) {
  return window['go']['main']['App']['Check'](arg1, arg2, arg3);
}

export function Diff(arg1, arg2) {
  return window['go']['main']['App']['Diff'](arg1, arg2);
}

export function FleetCheck(arg1) {
  return window['go']['main']['App']['FleetCheck'](arg1);
}

export function FleetConverge(arg1, arg2, arg3) {
  return window['go']['main']['App']['FleetConverge'](arg1, arg2, arg3);
}

export function FleetDiscover(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FleetDiscover'](arg1, arg2, arg3, arg4);
}

export function FleetFingerprint(arg1) {
  return window['go']['main']['App']['FleetFingerprint'](arg1);
}

export function FleetHealth(arg1, arg2) {
  return window['go']['main']['App']['FleetHealth'](arg1, arg2);
}

export function FleetRecover(arg1, arg2) {
  return window['go']['main']['App']['FleetRecover'](arg1, arg2);
}

export function FleetSnapshot(arg1) {
  return window['go']['main']['App']['FleetSnapshot'](arg1);
}

export function FleetTopology(arg1) {
  return window['go']['main']['App']['FleetTopology'](arg1);
}

export function MigrateApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['MigrateApply'](arg1, arg2, arg3);
}

export function MigrateGenerate(arg1, arg2) {
  return window['go']['main']['App']['MigrateGenerate'](arg1, arg2);
}

export function MonitorCheck(arg1, arg2) {
  return window['go']['main']['App']['MonitorCheck'](arg1, arg2);
}

export function MonitorLoadHistory(arg1) {
  return window['go']['main']['App']['MonitorLoadHistory'](arg1);
}

export function MonitorSnapshot(arg1, arg2) {
  return window['go']['main']['App']['MonitorSnapshot'](arg1, arg2);
}

export function MonitorWatchIsRunning() {
  return window['go']['main']['App']['MonitorWatchIsRunning']();
}

export function MonitorWatchStart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MonitorWatchStart'](arg1, arg2, arg3, arg4);
}

export function MonitorWatchStop() {
  return window['go']['main']['App']['MonitorWatchStop']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function QueryTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryTable'](arg1, arg2, arg3, arg4);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function Schema(arg1) {
  return window['go']['main']['App']['Schema'](arg1);
}

export function TableDiffRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TableDiffRows'](arg1, arg2, arg3, arg4, arg5);
}
