// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Diff(arg1, arg2) {
  return window['go']['main']['App']['Diff'](arg1, arg2);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function QueryTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryTable'](arg1, arg2, arg3, arg4);
}

export function Schema(arg1) {
  return window['go']['main']['App']['Schema'](arg1);
}

export function TableDiffRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TableDiffRows'](arg1, arg2, arg3, arg4, arg5);
}
